# Generated by Django 3.2 on 2021-04-30 16:23

from django.conf import settings
from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Otel ismi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Otel açıklaması')),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('country', models.CharField(max_length=50, verbose_name='Ülkte')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('owner', models.ForeignKey(on_delete=models.SET(hotels.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Otel sahibi')),
            ],
        ),
    ]
