# Generated by Django 3.2 on 2021-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Ülke'),
        ),
    ]
