# Generated by Django 3.2 on 2021-05-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20210501_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Oda numarası')),
                ('number_of_beds', models.IntegerField(verbose_name='Yatak sayısı')),
                ('price', models.FloatField(verbose_name='Oda fiyatı')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('title', models.CharField(max_length=100, verbose_name='İçerik başlığı')),
                ('detail', models.TextField(verbose_name='Oda detayları')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
