# Generated by Django 3.2 on 2021-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Kiralandı mı?'),
        ),
    ]
