# Generated by Django 3.2 on 2021-05-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_room_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_first_name', models.CharField(max_length=80, verbose_name='İsim')),
                ('to_last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Rezervasyon Tarihi')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('card_number', models.CharField(max_length=25, verbose_name='Kart numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='Mail adresi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.room', verbose_name='Kiralanan Oda')),
            ],
        ),
    ]
