# Generated by Django 3.2 on 2021-05-03 00:16

from django.conf import settings
from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(hotels.models.get_sentinel_user), related_name='have_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Otel sahibi'),
        ),
    ]
